-- ATAS: registros duplicados removidos. Cada par (numero, ano) deve existir uma unica vez.
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao)
VALUES (82, 2024, '2024-10-23', '2026-10-22', 2, 'Abertura de processo licitatório para Registro de Preços visando eventual e futura necessidade de serviços de manutenção corretiva em refrigerador, freezer, micro-ondas, fogão, máquina de lavar roupa, máquina de secar roupa, máquina de lavar louça industrial e fornecimento de peças novas para os referidos eletrodomésticos que estão inseridos nos prédios públicos municipais, em todas as Secretarias Municipais da Prefeitura Municipal de Imbé, conforme Estudo Técnico Preliminar em anexo', 1, '337/2026', '2026-03-13');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao)
VALUES (93, 2024, '2024-12-11', '2026-12-11', 1, 'Processo Licitatório visando o Registro de Preços para eventual e futura aquisição Gás Liquefeito de Petróleo (GLP), vasilhames tipo botijão de gás retornáveis e conjunto/kit para instalação de gás, para atender de forma ágil todas as Secretarias da Prefeitura Municipal de Imbé.', 1, '097/2026', '2026-01-21');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao)
VALUES (38, 2025, '2025-05-29', '2026-05-28', 2, 'Abertura de expediente, para futura contratação de empresas referente a manutenção de veículos leves, e motocicletas do executivo municipal.', 1, '1793/2025', '2025-10-17');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao)
VALUES (39, 2025, '2025-05-28', '2027-05-27', 2, 'Serviços de manutenção corretiva e preventiva, serviços de instalação, retirada e reinstalação de ar-condicionado, bem como o fornecimento de peças novas para os aparelhos de ar-condicionado                                                                                                                                                         Renovação da ARP 039/2025 em andamento', 1, '336/2026', '2026-03-13');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (46, 2025, '2025-07-09', '2026-07-08', 1, 'Trata-se de aquisição de Produtos de limpeza e higienização para os veículos e máquinas do executivo municipal.', 1, '2119/2025', '2025-12-29');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (47, 2025, '2025-07-14', '2026-07-13', 1, 'Trata-se de aquisição de Tubos PEAD, para atender às demandas de manutenção de vias alagadas', 1, '080/2026', '2026-01-16');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (48, 2025, '2025-07-29', '2026-07-28', 1, 'objeto do presente Registro de Preço para aquisição de coletes balísticos (tamanhos variados) para uso da Guarda Municipal de Imbé, por meio de ARP (Ata de Registro de Preços) na modalidade menor preço', 1, '572/2026', '2026-04-29');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (49, 2025, '2025-07-23', '2026-07-22', 1, 'Trata-se de Eventual e futura aquisição de Cadeiras e mobiliário para eventos para a Rede Municipal de Ensino.', 1, '1474/2025', '2025-08-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (50, 2025, '2025-07-31', '2026-07-30', 1, 'Trata-se de aquisição de Material De Expediente Complementar para atender de forma ágil, adequada e funcional as necessidades do Gabinete do Prefeito e das Secretarias Municipais.', 1, '055/2026', '2026-01-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (51, 2025, '2025-07-31', '2026-07-30', 1, 'TRATA-SE DE AQUISIÇÃO DE TINTAS, SOLVENTES E ACESSÓRIOS PARA PINTURA  - COMPLEMENTAR, para execução de serviços de manutenção e reparos de prédios, visando recuperar e vitalizar a pintura dos ambientes e edificações, zelando pela conservação e proteção do patrimônio público, nas quantidades, exigências e especificações estabelecidas em Termo de Referência. Documentos complementares em anexo.', 1, '056/2026', '2026-01-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (52, 2025, '2025-08-01', '2026-07-31', 1, 'Trata-se de aquisição de Pedra brita nº 04, pó de pedra e bica corrida, para a continuidade aos serviços de pavimentação, manutenção, e conservação das vias públicas do município de Imbé, visando os enchimentos de alicerces, base de asfalto, drenos, fundações, enchimentos e sub-base, nas quantidades, exigências, e especificações conforme memorando do Departamento de Engenharia nº 065/2025. Documentos complementares em anexo.', 1, '057/2026', '2026-01-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (53, 2025, '2025-08-15', '2026-08-14', 1, 'Futura e eventual aquisição de pregos - complementar, para suprir as demandas de serviços de marcenaria/carpintaria da Secretaria Municipal de Obras e Viação. Documentos complementares em anexo.', 1, '058/2026', '2026-01-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (54, 2025, '2025-08-20', '2026-08-19', 1, 'Carimbos e Borrachas de Polímero, para o atendimento ágil, adequado e funcional das necessidades do Gabinete do Prefeito e das Secretarias Municipais.', 1, '059/2026', '2026-01-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (56, 2025, '2025-09-05', '2026-09-04', 1, 'Eventual e futura aquisição de medicamentos para uso veterinário para o Departamento de Proteção Animal - DEPAN e Castramóvel. Estudo Técnico Preliminar, preços de referenciais e demais documentos anexos.', 1, '060/2026', '2026-01-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (55, 2025, '2025-09-01', '2026-08-31', 1, 'MATERIAIS DE USO COTIDIANO NAS UNIDADES DA REDE MUNICIPAL DE ENSINO E SETORES INERENTES A SECRETARIA DE EDUCAÇÃO', 1, '1726/2025', '2025-09-24');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (57, 2025, '2025-09-08', '2026-09-07', 1, 'Materiais para exercícios de fonoaudiologia para o Centro de Especialidades e CASTEAcolhe em nosso município.', 1, '095/2026', '2026-01-21');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (58, 2025, '2025-09-11', '2026-09-10', 1, 'Materiais e insumos médico-hospitalares para abastecimento das Unidades de Saúde do Município.', 1, '496/2026', '2026-04-08');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (59, 2025, '2025-09-15', '2026-09-14', 1, 'Fraldas descartáveis, geriátricas e infantis, para distribuição no município e também para atendimento de pacientes pontuais nas Unidades de Saúde, Pronto Atendimento e EMAD.', 1, '093/2026', '2026-01-21');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (60, 2025, '2025-09-15', '2026-09-14', 1, 'Pilhas e baterias para atender de forma ágil, adequada e funcional as necessidades do Gabinete do Prefeito e Secretarias Municipais.', 1, '061/2026', '2026-01-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (61, 2025, '2025-09-15', '2026-09-14', 1, 'Medicamentos pertencentes à Relação Municipal de Medicamentos Essenciais (REMUME), necessários para o atendimento das demandas da Farmácia Básica Municipal, garantindo assim a continuidade das ações de saúde e do tratamento dos pacientes de responsabilidade deste município para o ano de 2025.', 1, '092/2026', '2026-01-21');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (62, 2025, '2025-09-16', '2026-09-15', 1, 'Material de Construção, que será necessário à execução de serviços de manutenção em diversos prédios públicos deste município. A Secretaria de Obras e Viação gerencia a manutenção preventiva, corretiva e assertiva dos prédios públicos do município de Imbé.', 1, '2120/2025', '2025-12-29');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (63, 2025, '2025-09-23', '2026-09-22', 1, 'Confecção de medalhas e troféus personalizados para suprir as demandas de eventos, celebrações, shows e homenagens realizadas pelo município, pelo período de 12 (doze) meses.', 1, '918/2026', '2026-07-17');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (64, 2025, '2025-09-23', '2026-09-22', 1, 'Material destinado a pavimentação - BASE DE BRITA GRADUADA, PEDRA DE BASALTO IRREGULAR PARA CALÇAMENTO, AREIA PARA ATERRO LIMPA E SAIBRO BRITADO E PENEIRADO, visando a manutenção do pavimento deteriorado de diversas vias públicas e trechos do Município de Imbé, bem como, a pavimentação de ligações vicinais e trechos viários, onde inexiste pavimento.', 1, '248/2026', '2026-02-19');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (65, 2025, '2025-09-25', '2026-09-24', 1, 'Pedido de Abertura de Registro de Preço de Contratação de Empresa para impressão e montagem de carnês de IPTU para exercício 2026.', 1, '1729/2025', '2025-09-30');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (66, 2025, '2025-09-26', '2026-09-25', 1, 'Eventual e futura aquisição de equipamentos odontológicos, destinados aos consultórios odontológicos das Unidades de Saúde do município.', 1, '091/2026', '2026-01-21');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (67, 2025, '2025-10-13', '2026-10-12', 1, 'Playgrounds para atender as demandas das unidades escolares da Rede Municipal de Ensino.', 1, '1795/2025', '2025-10-17');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (68, 2025, '2025-10-15', '2026-10-14', 1, 'Edição e impressão de livros e agendas para registro de atividades dos alunos e servidores da Rede Municipal de Ensino.', 1, '1873/2025', '2025-11-11');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (69, 2025, '2025-10-16', '2026-10-15', 1, 'Medicamentos e medicamentos injetáveis para suprir a demanda da Secretaria de Saúde, incluindo almoxarifado da Saúde e consequentemente as Unidades de Pronto Atendimento e Farmácia Básica Municipal.', 1, '090/2026', '2026-01-21');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (70, 2025, '2025-10-17', '2026-10-17', 1, 'Trata-se de solicitação de abertura de procedimento licitatório, para eventual e futura aquisição de ferramentas manuais específicas, destinadas ao setor de serviços elétricos da Prefeitura. Conforme documentações em anexo.', 1, '062/2026', '2026-01-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (71, 2025, '2025-10-21', '2026-10-20', 1, 'Eletrodomésticos, condicionadores de ar e lavadora e secadora de pisos COMPLEMENTAR, para a Prefeitura Municipal de Imbé.', 1, '002/2026', '2026-01-05');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (72, 2025, '2025-10-21', '2026-10-20', 1, 'Materiais e insumos da área de suporte urinário (sondas), destinados para atendimento de pacientes das Unidades de Saúde e Pronto Atendimento do Município, bem como o abastecimento do Almoxarifado da Saúde.', 1, '497/2026', '2026-04-08');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (73, 2025, '2025-10-22', '2026-10-21', 1, 'Tecidos e aviamentos para atender a Rede Municipal de Ensino.', 1, '1831/2025', '2025-10-30');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (74, 2025, '2025-10-29', '2026-10-28', 1, 'Telas interativas e suporte para atender as demandas das unidades escolares da Rede Municipal de Ensino.', 1, '1845/2025', '2025-11-03');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (75, 2025, '2025-11-03', '2026-11-02', 1, 'Registro de preços para aquisição de  Materiais Personalizados para Premiações culturais e artísticas e comemoração de eventos, visando atender as necessidades da Secretaria Municipal de Educação', 1, '1864/2025', '2025-11-07');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (76, 2025, '2025-11-03', '2026-11-02', 1, 'Materiais e insumos médico-hospitalares para abastecimento das Unidades de Saúde do Município. Este Grupo III da "Ata MMH" engloba "Itens de Uso Geral" necessários para tais unidades.', 1, '498/2026', '2026-04-08');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (77, 2025, '2025-11-04', '2026-11-03', 1, 'Tubos de Concreto e Artefatos de Cimento, que será necessário à execução de serviços de manutenção em diversas ruas deste município.', 1, '003/2026', '2026-01-05');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (78, 2025, '2025-11-11', '2026-11-10', 1, 'Aquisição de larvicidas, raticidas e inseticidas para a Vigilância Em Saúde, produtos usados no combate e controle de pragas tais como o mosquito da dengue (Aedes Aegypti).', 1, '106/2026', '2026-01-22');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (79, 2025, '2025-11-17', '2026-11-16', 1, 'Materiais e instrumentos odontológicos, destinados aos consultórios de odontologia das Unidades de Saúde do Município.', 1, '087/2026', '2026-01-21');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (80, 2025, '2025-11-26', '2026-11-25', 1, 'Pisos modulares e emborrachado para atender as demandas das unidades escolares da Rede Municipal de Ensino.', 1, '1961/2025', '2025-11-28');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (81, 2025, '2025-11-26', '2026-11-25', 1, 'Registro de Preços, visando eventual e futura aquisição de Kits Ovitrampas + Levedo e Reagente Cloro para as Vigilâncias Ambiental e Sanitária do Município de Imbé.', 1, '086/2026', '2026-01-21');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (83, 2025, '2025-11-27', '2026-11-26', 1, 'Colocação de meio-fio de concreto, mão de obra e material, incluindo a remoção do meio-fio existente, quando houver, conforme exigências e especificações estabelecidas em Memorial Descritivo e documentos complementares em anexo.', 1, '1979/2025', '2025-12-02');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (84, 2025, '2025-12-04', '2026-12-03', 1, 'Insumos para material curativo, destinado à abastecer nossos serviços de Saúde do Munícipio, como Unidades de Saúde Básica, Pronto Atendimento e Almoxarifado da Saúde.', 1, '499/2026', '2026-04-08');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (85, 2025, '2025-12-04', '2026-12-03', 2, 'Locação de MOTONIVELADORA visando o atendimento das demandas da Secretaria Municipal de Obras e Viação do Município de Imbé/RS', 1, '2082/2025', '2025-12-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (86, 2025, '2025-12-09', '2026-12-08', 2, 'Registro de Preço para futura contratação de empresa especializada para fornecimento, instalação e manutenção de sistema de rastreamento veicular via tecnologia GPS/GPRS para os veículos e máquinas da frota da Prefeitura Municipal de Imbé.', 1, '2105/2025', '2025-12-18');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (87, 2025, '2026-01-07', '2027-01-06', 2, 'Pneus diversos para a frota do Executivo Municipal.', 1, '050/2026', '2026-01-09');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (1, 2026, '2026-01-20', '2027-01-19', 1, 'Aquisição de Mobiliário Escolar para a Rede Municipal de Ensino.', 1, '107/2026', '2026-01-22');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (2, 2026, '2026-01-27', '2027-01-26', 1, 'Material de Higiene e Limpeza para atender de forma ágil, adequada e funcional as necessidades do Gabinete do Prefeito e das Secretarias Municipais.', 1, '141/2026', '2026-02-03');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (3, 2026, '2026-01-27', '2027-01-26', 1, 'Serviços impressos - folder e jornais, tendo em vista a confecção de materiais que são necessários para campanhas publicitárias e educativas da Prefeitura Municipal de Imbé, atendendo as demandas de todas as secretarias.', 1, '317/2026', '2026-03-04');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (5, 2026, '2026-02-03', '2027-02-02', 1, 'Placas inaugurais e totens para atender a demanda de inaugurações de prédios de uso municipal e para sinalização destes locais.', 1, '200/2026', '2026-02-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (6, 2026, '2026-02-04', '2027-02-03', 1, 'Registro de Preços para fornecimento de Medicamentos pertencentes a relação municipal de      medicamentos essenciais (REMUME).', 1, '201/2026', '2026-02-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (7, 2026, '2026-02-04', '2027-02-03', 2, 'Serviços gráficos, tendo em vista as necessidades do executivo municipal.', 1, '767/2026', '2026-06-11');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (8, 2026, '2026-02-06', '2027-02-05', 1, 'Registro de preços de cestos básicos, com itens de gêneros alimentícios, visando suprir necessidades das Secretarias de Desenvolvimento Social.', 1, '202/2026', '2026-02-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (9, 2026, '2026-02-09', '2027-02-08', 1, 'Chamamento público para aquisição de gêneros alimentícios da agricultura familiar, em atendimento a Lei nº 11.947 de 16/07/2009, Resolução nº 06/2020 e 03/2025 do FNDE.', 1, '427/2026', '2026-03-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (10, 2026, '2026-02-11', '2027-02-10', 1, 'Registro de preços visando futura e eventual aquisição de materiais/utensílios de cozinha para as Unidades Escolares da Rede Municipal.', 1, '206/2026', '2026-02-12');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (11, 2026, '2026-02-13', '2027-02-12', 1, 'Aquisição de paradas de ônibus cobertas com estruturas modulares metálicas galvanizadas e que sejam remanejáveis, visando atender de forma adequada, funcional e segura os usuários do transporte público.', 1, '270/2026', '2026-02-13');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (12, 2026, '2026-03-04', '2027-03-03', 1, 'Aquisição de equipamentos e acessórios tecnológicos por meio de Registro de Preços, visando modernizar e ampliar a infraestrutura de tecnologia da informação е comunicação do Município de Imbé.', 1, '318/2026', '2026-03-10');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (13, 2026, '2026-03-11', '2027-03-10', 1, 'objeto do presente o Registro de Preço, para futura e eventual aquisição de PEDRA MATACÃO, necessária para execução de obras de contenção e estabilização, devido à sua alta resistência e durabilidade.', 1, '834/2026', '2026-06-18');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (14, 2026, '2026-04-07', '2027-04-06', 1, 'Registro de preços visando futura e eventual aquisição de Laboratórios de Ciências para atender as demandas das unidades escolares da rede municipal.', 1, '502/2026', '2026-04-13');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (15, 2026, '2026-04-01', '2027-03-30', 1, 'que tem como objeto, fornecimento de cabines sanitárias e container sanitário para atender as demandas dos eventos realizados pela Secretaria Municipal de Turismo.', 1, '764/2026', '2026-06-11');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (16, 2026, '2026-03-27', '2027-03-26', 1, 'objeto  Registro de Preço visando atual e futura contratação de empresa para prestação de serviços de controle de pragas urbanas (desinsetização, desratização e expurgo de morcegos) e limpeza e desinfecção das caixas d’água para os prédios, setores e unidades vinculados as Secretarias do Município.', 1, '560/2026', '2026-04-28');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (17, 2026, '2026-04-08', '2027-04-07', 1, 'Constitui objeto do presente o Registro de Preço, para futura e eventual aquisição de material hidráulico, visando atender às demandas relacionadas à manutenção, reparo e operação de instalações hidráulicas em prédios e unidades sob responsabilidade da Prefeitura Municipal.', 1, '740/2026', '2026-06-03');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (18, 2026, '2026-04-13', '2027-04-12', 1, 'Abertura do processo licitatório para Registro de preços de kit de capa de tablets e equipamento para sonorização de eventos para atender as demandas do calendário oficial das unidades escolares da Rede Municipal de Ensino e de segurança dos equipamentos utilizados em atividades cotidianas.', 1, '558/2026', '2026-04-17');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (19, 2026, '2026-04-27', '2027-04-26', 1, 'Constitui objeto do presente o Registro de Preço, para eventual e futura aquisição de EQUIPAMENTOS E FERRAMENTAS ESPECÍFICAS, necessários para atender às demandas operacionais das equipes responsáveis pela execução de serviços de manutenção, reparos e apoio às atividades das Secretarias Municipais.', 1, '587/2026', '2026-04-27');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (20, 2026, '2026-04-07', '2027-04-06', 1, 'Constitui objeto do presente Registro de Preço visando futuras aquisições de veículos leves para a frota do executivo municipal.', 1, '860/2026', '2026-06-26');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (21, 2026, '2026-04-27', '2027-04-26', 1, 'Abertura do Processo Licitatório para Registro de Preços para edição e impressão de agendas para registro de atividades dos alunos e servidores da Rede Municipal de Ensino.', 1, '616/2026', '2026-04-28');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (22, 2026, '2026-04-07', '2027-04-06', 1, 'Registro de Preços, visando eventual e futura aquisição de produtos destinados ao setor/Equipe Multiprofissional de Atendimento Domiciliar (EMAD) e o Programa Melhor em Casa.', 1, '561/2026', '2026-04-29');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (23, 2026, '2026-04-27', '2027-04-26', 1, 'Constitui objeto do presente o Registro Preço para Contratação de serviços de comunicação visual, tendo em vista a confecção de materiais que são necessários para identificar ações e iniciativas institucionais, bem como de prédios e bens da Prefeitura Municipal de Imbé, atendendo demandas de todas as Secretarias Municipais.', 1, '562', '2026-04-28');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (24, 2026, '2026-04-09', '2027-04-08', 1, 'Registro de Preços, visando eventual e futura aquisição de materiais e equipamentos necessários para o funcionamento do Centro de Fisioterapia Municipal.', 1, '511/2026', '2026-04-23');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (25, 2026, '2026-04-15', '2027-04-14', 1, 'Abertura do processo licitatório para Registro de preços de Materiais Esportivos para atender a Rede Municipal de Ensino.', 1, '652/2026', '2026-05-25');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (26, 2026, '2026-05-06', '2027-05-05', 1, 'Abertura do processo licitatório para Registro de Preços de Gêneros Alimentícios, para atender a Secretaria de Educação, Assistência Social e demais Secretarias', 1, '612/2026', NULL);
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (27, 2026, '2026-04-17', '2027-04-16', 1, 'Registro de preço de material personalizado, sendo que a aquisição destes materiais é fundamental para assegurar a continuidade das campanhas, eventos e premiações que envolvem a Secretaria Municipal de Saúde e o NUMESC.', 1, '559/2026', '2026-04-24');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (28, 2026, '2026-04-22', '2027-04-21', 1, 'Constitui objeto do presente Registro de preço para futura e eventual aquisição de materiais de demarcação e sinalização de trânsito vertical e horizontal, a fim de atender as demandas do Departamento de Trânsito.', 1, '709', NULL);
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (29, 2026, '2026-04-27', '2027-04-26', 1, 'Constitui objeto do presente o Registro de Preço, para futura e eventual aquisição de madeiras brutas e beneficiadas, destinadas ao atendimento das demandas de manutenção, reparos e pequenas obras. A madeira é frequentemente utilizada em diversas estruturas públicas, como abrigos, cercamentos, mobiliários simples, suportes, revestimentos, passarelas, contenções, entre outros. Documentos complementares em anexo.', 1, '564/2026', '2026-04-27');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (30, 2026, '2026-04-27', '2027-04-26', 1, 'Constitui objeto do presente o Registro de preço de materiais de ferragens e utensílios diversos, essenciais para a manutenção, reparos e pequenas adequações nas instalações dos prédios públicos. Os itens solicitados permitirão a execução eficiente de serviços internos, garantindo o bom funcionamento das atividades e a preservação do patrimônio público.', 1, '574/2026', '2026-04-28');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (31, 2026, '2026-04-29', '2027-04-28', 1, 'Constitui objeto do presente o Registro de Preços, para eventual e futura aquisição de material elétrico – cabos e fios. Material necessário para manutenção, ampliação e/ou reposição das instalações elétricas dos prédios públicos, vias e demais estruturas sob responsabilidade do Município.', 1, '654/2026', '2026-05-25');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (33, 2026, '2026-05-05', '2027-05-04', 2, 'Registro de preços para aquisição de sistemas de controle de acesso biométrico (tipo facial) para gerenciar a entrada e saída de funcionários dos prédios da Prefeitura Municipal de Imbé.', 1, '598/2026', '2026-05-05');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (35, 2026, '2026-05-13', '2027-05-12', 2, 'Trata-se da necessidade da Prefeitura Municipal de Imbé de ter fornecimento de sonorização indoor e outdoor, painel de LED, serviços de iluminação, destinados a atender às demandas e necessidades da Secretaria de Turismo pelo período de 12 (doze) meses, conforme ETP em anexo.', 1, '770/2026', '2026-06-15');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (36, 2026, '2026-05-14', '2027-05-13', 1, 'Constitui objeto do presente o Registro de Preço, para futura e eventual contratação de serviço manutenção de vias públicas, em diversas ruas do município de Imbé.', 1, '746/2026', '2026-06-03');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (37, 2026, '2026-05-21', '2027-05-20', 1, 'Constitui objeto do presente o Registro de Preço, visando à futura e eventual aquisição de arruelas, brocas e parafusos, visando atender às demandas rotineiras dos serviços de manutenção, reparos e pequenos ajustes realizados nas dependências e estruturas pertencentes a esta Administração.', 1, '759/2026', '2026-06-09');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (38, 2026, '2026-05-21', '2026-05-20', 1, 'Registro de Preços para eventual e futura aquisição de  papeis encadernados para atender de forma ágil, adequada e funcional as necessidades do Gabinete do Prefeito e das Secretarias Municipais', 1, '869/2026', '2026-07-03');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (39, 2026, '2026-05-26', '2027-05-25', 1, 'Constitui objeto do presente o Registro de preços para futura e eventual aquisição de PREGOS, para suprir as demandas de serviços de marcenaria/carpintaria da Secretaria Municipal de Obras e Viação.', 1, '741/2026', '2026-06-03');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (41, 2026, '2026-06-01', '2027-05-30', 1, 'Registro de Preços visando eventual e futura aquisição de uniformes e EPI’s para facilitarem a identificação dos servidores', 1, '778/2026', '2026-06-16');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (42, 2026, '2026-06-15', '2027-06-14', 1, 'Constitui objeto do presente o Registro de Preço, para eventual e futura aquisição de equipamentos de proteção individual (EPI’s) e uniformes, destinados a atender à demanda contínua das atividades desempenhadas pelos servidores municipais, assegurando condições adequadas de segurança, padronização e identificação funcional.', 1, '836/2026', '2026-06-25');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (43, 2026, '2026-06-02', '2027-06-01', 1, 'Registro de Preços, visando eventual e futura aquisição de insumos e materiais hospitalares, englobando produtos que servem como EPI (Equipamento de Proteção Individual) para abastecimento das nossas unidades e serviços de saúde do município.', 1, '765/2026', '2026-06-11');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (44, 2026, '2026-06-16', '2027-06-15', 1, 'Registro de Preços para eventual e futura aquisição de Dispositivos IoT (relés) para controle das luminárias públicas da Iluminação Pública no Município de Imbé/RS, com o objetivo de viabilizar o controle remoto, monitoramento em tempo real e gestão dos ativos de iluminação pública, promovendo maior eficiência energética, melhoria na prestação do serviço e otimização dos recursos municipais', 1, '857/2026', '2026-06-26');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (45, 2026, '2026-06-16', '2027-06-15', 1, 'Registro de Preços, visando eventual e futura aquisição de testes rápidos para detecção de vírus como COVID e/ou Influenza e dengue, bem como testes de gravidez e tiras para testagem de índices de glicemia, com a finalidade de garantir os materiais necessários para funcionamento das Unidades de Pronto Atendimento e em nossas Unidades Básica de Saúde (UBS), bem como para distribuição gratuita aos pacientes que necessitam das tiras reagentes.', 1, '821/2026', '2026-06-17');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (46, 2026, '2026-06-22', '2027-06-21', 1, 'Registro de Preço, para eventual e futura aquisição de lâmpadas LED, material necessário para atender à demanda contínua de reposição da iluminação nos prédios e dependências municipais. As lâmpadas são utilizadas em ambientes administrativos, áreas de circulação e demais espaços que demandam iluminação adequada para o funcionamento regular das atividades públicas.', 1, '868/2026', '2026-07-03');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (47, 2026, '2026-06-24', 'None', 2, 'Registro de Preços, visando eventual e futura contratação de empresa especializada na prestação de serviços de lavanderia hospitalar para as Unidades de Pronto Atendimento do Município de Imbé.', 1, '867/2026', '2026-07-03');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (51, 2026, '2026-07-27', '2027-07-26', 1, 'Registro de Preço, para eventual e futura aquisição de brinquedos pedagógicos visando atender as necessidades das escolas Municipais da Rede Municipal.', 1, NULL, NULL);
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (82, 2024, '2024-10-23', '2026-10-22', 2, 'Abertura de processo licitatório para Registro de Preços visando eventual e futura necessidade de serviços de manutenção corretiva em refrigerador, freezer, micro-ondas, fogão, máquina de lavar roupa, máquina de secar roupa, máquina de lavar louça industrial e fornecimento de peças novas para os referidos eletrodomésticos que estão inseridos nos prédios públicos municipais, em todas as Secretarias Municipais da Prefeitura Municipal de Imbé, conforme Estudo Técnico Preliminar em anexo', 1, '337/2026', '2026-03-13');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (93, 2024, '2024-12-11', '2026-12-11', 1, 'Processo Licitatório visando o Registro de Preços para eventual e futura aquisição Gás Liquefeito de Petróleo (GLP), vasilhames tipo botijão de gás retornáveis e conjunto/kit para instalação de gás, para atender de forma ágil todas as Secretarias da Prefeitura Municipal de Imbé.', 1, '097/2026', '2026-01-21');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (38, 2025, '2025-05-29', '2026-05-28', 2, 'Abertura de expediente, para futura contratação de empresas referente a manutenção de veículos leves, e motocicletas do executivo municipal.', 1, '1793/2025', '2025-10-17');
INSERT INTO ata_registro_preco (numero, ano, data_inicio, data_fim, tipo_id, objeto, ativo_id, portaria_designacao, data_designacao) 
VALUES (39, 2025, '2025-05-28', '2027-05-27', 2, 'Serviços de manutenção corretiva e preventiva, serviços de instalação, retirada e reinstalação de ar-condicionado, bem como o fornecimento de peças novas para os aparelhos de ar-condicionado                                                                                                                                                         Renovação da ARP 039/2025 em andamento', 1, '336/2026', '2026-03-13');
