spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://192.168.0.236:3306/contract-management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull}
    username: ${DB_USERNAME:estagiario}
    password: ${DB_PASSWORD:Prefeitura}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    open-in-view: false

server:
  port: ${PORT:8081}
  address: 0.0.0.0
  servlet:
    context-path: /api

logging:
  level:
    com.contract_management: ${LOG_LEVEL:DEBUG}